[Distributor]
IP = "127.0.0.1"
Port = "19933"

    [Distributor.TLS]
    CertLoc = "../private/cert.pem"
    KeyLoc = "../private/key.pem"

    [Distributor.IMAP]
    Greeting = "Pluto ready."

    [Distributor.Auth]
    Adaptor = "postgres"
    IP = "127.0.0.1"
    Port = "5432"
    Database = "pluto"
    User = "pluto"