[Distributor]
IP = "127.0.0.1"
Port = "19933"
AuthAdapter = "AuthFile"

    [Distributor.PublicTLS]
    CertLoc = "../private/public-distributor-cert.pem"
    KeyLoc = "../private/public-distributor-key.pem"

    [Distributor.InternalTLS]
    CertLoc = "../private/internal-distributor-cert.pem"
    KeyLoc = "../private/internal-distributor-key.pem"

    [Distributor.IMAP]
    Greeting = "Pluto ready."

    [Distributor.AuthFile]
    File = "test-users.txt"
    Separator = ";"


[Workers]

    [Workers.worker-1]
    IP = "127.0.0.1"
    Port = "20001"
    UserStart = 1
    UserEnd = 10

        [Workers.worker-1.TLS]
        CertLoc = "../private/internal-worker-1-cert.pem"
        KeyLoc = "../private/internal-worker-1-key.pem"

    [Workers.worker-2]
    IP = "127.0.0.1"
    Port = "20002"
    UserStart = 11
    UserEnd = 20

        [Workers.worker-2.TLS]
        CertLoc = "../private/internal-worker-2-cert.pem"
        KeyLoc = "../private/internal-worker-2-key.pem"

    [Workers.worker-3]
    IP = "127.0.0.1"
    Port = "20003"
    UserStart = 21
    UserEnd = 30

        [Workers.worker-3.TLS]
        CertLoc = "../private/internal-worker-3-cert.pem"
        KeyLoc = "../private/internal-worker-3-key.pem"


[Storage]
IP = "127.0.0.1"
Port = "21000"

    [Storage.TLS]
    CertLoc = "../private/internal-storage-cert.pem"
    KeyLoc = "../private/internal-storage-key.pem"